## Web Scraping IMDb Top 250 Movies

### Table of Contents
- Purpose/objective <br>
- Tools Used <br>
- Workflow <br>
- Code Implementation <br>
- Results <br>
- Conclusion <br>
- Showcases

### Purpose/Objective:
<div style='align-text: justify'>The purpose of this project is to demonstrate proficiency in web scraping using Python libraries such as BeautifulSoup and requests. The objective is to extract the IMDb Top 250 movies from the IMDb website, create a structured dataset, and save it as a CSV file. This project serves as a showcase of web scraping skills for potential employers.
</div>


### Tools Used:
##### Python:
The programming language used for the entire project.
##### BeautifulSoup:
A Python library for parsing HTML and XML documents.
##### Requests:
A Python library for making HTTP requests.
##### Pandas: 
A Python library for data manipulation.
#####  CSV:
A file format used for storing tabular data.

### Workflow:
##### 1. Scraping IMDb Top 250 List 
The project starts by sending an HTTP GET request to the IMDb Top 250 list page using the requests library. BeautifulSoup is then used to parse the HTML content of the page and extract relevant information such as movie rank, title, release_year, and rating vote.
##### 2. Data Processing 
After extracting the movie data, it is processed to split the "rank_title" into "rank" and "title", and "rating_votes" into "rating" and "votes" for better organization.
##### 3. Creating DataFrame 
The processed data is structured into a pandas DataFrame named 'Top_movies'.
##### 4. Exporting to CSV
Finally, the 'Top_movies' DataFrame is exported to a CSV file named 'imdb_top_movies.csv' for further analysis or storage.
##### 5. Code Implementation
The Python code consists of several steps, including importing necessary libraries, sending HTTP requests, parsing HTML content, processing data, creating a DataFrame, and exporting to CSV. Error handling is also included to manage exceptions that may occur during the process.

### Showcases

#### 1. Scraping Data

##### Import the required Python libraries for the scraping, creating DataFrame, and exporting to the CSV file process.

In [8]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

##### Scrap IMDb top 250 movies list.

In [26]:
# URL of the IMDb Top 250 list
url = 'https://www.imdb.com/chart/top/'

# Headers to mimic a browser request
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

# Class names of elements containing movie metadata and details
ul_class = "ipc-metadata-list ipc-metadata-list--dividers-between sc-a1e81754-0 eBRbsI compact-list-view ipc-metadata-list--base"
div_class = "sc-b189961a-0 hBZnfJ cli-children"

try:
    # Send an HTTP GET request to the URL with headers
    response = requests.get(url, headers=headers)
    response.raise_for_status()  # Raise an exception for HTTP errors

    # Create a BeautifulSoup object to parse the HTML content
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find all movie <div> elements within the specified <ul> element
    movies = soup.find('ul', class_=ul_class).find_all('div', class_=div_class)

    # Iterate over each movie <div> element
    for movie in movies:
        # Find the <h3> element containing movie title
        rank_title = movie.find('h3', class_="ipc-title__text").text
        
        # Find the <div> element containing release year and then find the <span> within it
        release_year = movie.find('div', class_="sc-b189961a-7 feoqjK cli-title-metadata").span.text
        
        # Find the <span> element containing rating votes
        rating_votes = movie.find('span', class_="sc-b189961a-1 kcfvgk").span.text

        # Print movie details
        print("Rank and Title:", rank_title)
        print("Release_Year:", release_year)
        print("Rating and Votes:", rating_votes)
  
        # Stop after the first iteration     
        break
except Exception as e:
    # Catch any exceptions and print the error message
    print(e)

Rank and Title: 1. The Shawshank Redemption
Release_Year: 1994
Rating and Votes: 9.3Â (2.9M)

##### Split rank_title as "rank" and "title" , and rating_votes as "rating" and "votes".

In [28]:


url = 'https://www.imdb.com/chart/top/'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

ul_class="ipc-metadata-list ipc-metadata-list--dividers-between sc-a1e81754-0 eBRbsI compact-list-view ipc-metadata-list--base"
li_class="ipc-metadata-list-summary-item sc-10233bc-0 iherUv cli-parent"
div_class = "sc-b189961a-0 hBZnfJ cli-children" 
try:
    response = requests.get(url, headers=headers)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, 'html.parser')
    movies = soup.find('ul', class_=ul_class).find_all('div', class_= div_class)
    
    for movie in movies:
        rank = movie.find('h3', class_="ipc-title__text").text.split('.')[0]
        title= movie.find('h3', class_="ipc-title__text").text.split('.')[-1]
        release_year = movie. find('div', class_="sc-b189961a-7 feoqjK cli-title-metadata").span.text
        rating = movie.find('span', class_="sc-b189961a-1 kcfvgk").span.text.split()[0]
        votes = movie.find('span', class_="sc-b189961a-1 kcfvgk").span.text.split()[-1].strip('()')
        
        print("Rank:", rank)
        print("Title:", title)
        print("Year:",release_year)
        print("Rating", rating) 
        print("Vote",votes)
        break
        
        
except Exception as e:
    print(e)

Rank: 1
Title:  The Shawshank Redemption
Year: 1994
Rating 9.3
Vote 2.9M

##### Display the elements in a single line.

In [29]:
url = 'https://www.imdb.com/chart/top/'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

ul_class = "ipc-metadata-list ipc-metadata-list--dividers-between sc-a1e81754-0 eBRbsI compact-list-view ipc-metadata-list--base"
li_class = "ipc-metadata-list-summary-item sc-10233bc-0 iherUv cli-parent"
div_class = "sc-b189961a-0 hBZnfJ cli-children" 

try:
    response = requests.get(url, headers=headers)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, 'html.parser')
    movies = soup.find('ul', class_=ul_class).find_all('div', class_=div_class)
    
    for movie in movies:
        # Find the <h3> element containing movie rank and title, then split it and get the rank value 
        rank = movie.find('h3', class_="ipc-title__text").text.split('.')[0]
        
        #Find the <h3> element containing movie rank and title, then split it and get the title value 
        title = movie.find('h3', class_="ipc-title__text").text.split('.')[-1]
        
        # Find the <div> element containing release year and extract the text
        release_year = movie.find('div', class_="sc-b189961a-7 feoqjK cli-title-metadata").span.text
        
        # Find the <span> element containing the rating and votes, split it and get the rating value
        rating = movie.find('span', class_="sc-b189961a-1 kcfvgk").span.text.split()[0]
        
        # Find the <span> element containing the rating and votes, split it and get the votes count
        vote = movie.find('span', class_="sc-b189961a-1 kcfvgk").span.text.split()[-1].strip('()')
        
        # Print the rank, title, release year, rating, and votes
        print("Rank:", rank)
        print("Title:", title)
        print("Year:",release_year)
        print("Rating", rating) 
        print("Votes", vote)
        
        # Stop after processing the first movie
        break
        
except Exception as e:
    # Print any exception that occurs during the process
    print(e)

Rank: 1
Title:  The Shawshank Redemption
Year: 1994
Rating 9.3
Votes 2.9M

##### Display all the top-rated movies.

In [5]:
url = 'https://www.imdb.com/chart/top/'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

ul_class="ipc-metadata-list ipc-metadata-list--dividers-between sc-a1e81754-0 eBRbsI compact-list-view ipc-metadata-list--base"
li_class="ipc-metadata-list-summary-item sc-10233bc-0 iherUv cli-parent"
div_class = "sc-b189961a-0 hBZnfJ cli-children" 
try:
    response = requests.get(url, headers=headers)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, 'html.parser')
    movies = soup.find('ul', class_=ul_class).find_all('div', class_= div_class)
    
    
    for movie in movies:
        rank = movie.find('h3', class_="ipc-title__text").text.split('.')[0]
        title= movie.find('h3', class_="ipc-title__text").text.split('.')[-1]
        release_year = movie. find('div', class_="sc-b189961a-7 feoqjK cli-title-metadata").span.text
        rating = movie.find('span', class_="sc-b189961a-1 kcfvgk").span.text.split()[0]
        votes = movie.find('span', class_="sc-b189961a-1 kcfvgk").span.text.split()[-1].strip('()')
       # Display the elements in a single line 
        print(rank, title,release_year, rating, votes)
        
            
except Exception as e:
    print(e)

1  The Shawshank Redemption 1994 9.3 2.9M
2  The Godfather 1972 9.2 2M
3  The Dark Knight 2008 9.0 2.9M
4  The Godfather Part II 1974 9.0 1.4M
5  12 Angry Men 1957 9.0 866K
6  Schindler's List 1993 9.0 1.5M
7  The Lord of the Rings: The Return of the King 2003 9.0 2M
8  Pulp Fiction 1994 8.9 2.2M
9  The Lord of the Rings: The Fellowship of the Ring 2001 8.9 2M
10  The Good, the Bad and the Ugly 1966 8.8 812K
11  Forrest Gump 1994 8.8 2.3M
12  The Lord of the Rings: The Two Towers 2002 8.8 1.8M
13  Fight Club 1999 8.8 2.3M
14  Inception 2010 8.8 2.6M
15  Star Wars: Episode V - The Empire Strikes Back 1980 8.7 1.4M
16  The Matrix 1999 8.7 2.1M
17  Goodfellas 1990 8.7 1.3M
18  One Flew Over the Cuckoo's Nest 1975 8.7 1.1M
19  Se7en 1995 8.6 1.8M
20  Interstellar 2014 8.7 2.1M
21  It's a Wonderful Life 1946 8.6 499K
22  Dune: Part Two 2024 8.7 384K
23  Seven Samurai 1954 8.6 367K
24  The Silence of the Lambs 1991 8.6 1.5M
25  Saving Private Ryan 1998 8.6 1.5M
26  City of God 2002 8.6 801K
27  Life Is Beautiful 1997 8.6 744K
28  The Green Mile 1999 8.6 1.4M
29  Terminator 2: Judgment Day 1991 8.6 1.2M
30  Star Wars: Episode IV - A New Hope 1977 8.6 1.5M
31  Back to the Future 1985 8.5 1.3M
32  Spirited Away 2001 8.6 850K
33  The Pianist 2002 8.5 913K
34  Parasite 2019 8.5 961K
35  Psycho 1960 8.5 719K
36  Spider-Man: Across the Spider-Verse 2023 8.6 370K
37  Gladiator 2000 8.5 1.6M
38  The Lion King 1994 8.5 1.1M
39  LÃ©on: The Professional 1994 8.5 1.2M
40  The Departed 2006 8.5 1.4M
41  American History X 1998 8.5 1.2M
42  Whiplash 2014 8.5 990K
43  The Prestige 2006 8.5 1.4M
44  Grave of the Fireflies 1988 8.5 311K
45  Harakiri 1962 8.6 69K
46  The Usual Suspects 1995 8.5 1.1M
47  Casablanca 1942 8.5 606K
48  The Intouchables 2011 8.5 930K
49  Cinema Paradiso 1988 8.5 283K
50  Modern Times 1936 8.5 260K
51  Rear Window 1954 8.5 522K
52  Once Upon a Time in the West 1968 8.5 349K
53  Alien 1979 8.5 952K
54  City Lights 1931 8.5 196K
55  Django Unchained 2012 8.5 1.7M
56  Apocalypse Now 1979 8.4 711K
57  Memento 2000 8.4 1.3M
58  12th Fail 2023 9.0 112K
59  WALLÂ·E 2008 8.4 1.2M
60  Raiders of the Lost Ark 1981 8.4 1M
61  The Lives of Others 2006 8.4 411K
62  1950 8.4 237K
63  Paths of Glory 1957 8.4 212K
64  Avengers: Infinity War 2018 8.4 1.2M
65  Spider-Man: Into the Spider-Verse 2018 8.4 672K
66  Witness for the Prosecution 1957 8.4 138K
67  The Shining 1980 8.4 1.1M
68  The Great Dictator 1940 8.4 237K
69  Aliens 1986 8.4 763K
70  Inglourious Basterds 2009 8.4 1.6M
71  The Dark Knight Rises 2012 8.4 1.8M
72  Strangelove or: How I Learned to Stop Worrying and Love the Bomb 1964 8.4 518K
73  American Beauty 1999 8.3 1.2M
74  Oldboy 2003 8.3 636K
75  Coco 2017 8.4 591K
76  Amadeus 1984 8.4 428K
77  Toy Story 1995 8.3 1.1M
78  Das Boot 1981 8.4 264K
79  Avengers: Endgame 2019 8.4 1.3M
80  Braveheart 1995 8.3 1.1M
81  Joker 2019 8.4 1.5M
82  Princess Mononoke 1997 8.3 434K
83  Good Will Hunting 1997 8.3 1.1M
84  2016 8.4 321K
85  Once Upon a Time in America 1984 8.3 378K
86  High and Low 1963 8.4 53K
87  3 Idiots 2009 8.4 435K
88  Singin' in the Rain 1952 8.3 261K
89  Capernaum 2018 8.4 105K
90  Requiem for a Dream 2000 8.3 899K
91  Come and See 1985 8.4 97K
92  Toy Story 3 2010 8.3 893K
93  Star Wars: Episode VI - Return of the Jedi 1983 8.3 1.1M
94  Eternal Sunshine of the Spotless Mind 2004 8.3 1.1M
95  Oppenheimer 2023 8.3 731K
96  The Hunt 2012 8.3 365K
97  2001: A Space Odyssey 1968 8.3 720K
98  Reservoir Dogs 1992 8.3 1.1M
99  Ikiru 1952 8.3 88K
100  Lawrence of Arabia 1962 8.3 315K
101  The Apartment 1960 8.3 197K
102  North by Northwest 1959 8.3 346K
103  Incendies 2010 8.3 201K
104  Citizen Kane 1941 8.3 466K
105  Vertigo 1958 8.3 427K
106  M 1931 8.3 169K
107  Double Indemnity 1944 8.3 168K
108  Scarface 1983 8.3 917K
109  Full Metal Jacket 1987 8.3 791K
110  AmÃ©lie 2001 8.3 794K
111  Heat 1995 8.3 720K
112  A Clockwork Orange 1971 8.3 882K
113  Up 2009 8.3 1.1M
114  To Kill a Mockingbird 1962 8.3 333K
115  The Sting 1973 8.3 280K
116  A Separation 2011 8.3 259K
117  Indiana Jones and the Last Crusade 1989 8.2 811K
118  Die Hard 1988 8.2 946K
119  Metropolis 1927 8.3 186K
120  Like Stars on Earth 2007 8.3 207K
121  Snatch 2000 8.2 911K
122  Hamilton 2020 8.3 114K
123  Confidential 1997 8.2 618K
124  1917 2019 8.2 676K
125  Bicycle Thieves 1948 8.3 175K
126  Taxi Driver 1976 8.2 921K
127  Downfall 2004 8.2 375K
128  Dangal 2016 8.3 211K
129  For a Few Dollars More 1965 8.2 275K
130  Batman Begins 2005 8.2 1.6M
131  The Wolf of Wall Street 2013 8.2 1.6M
132  Some Like It Hot 1959 8.2 284K
133  Green Book 2018 8.2 573K
134  The Kid 1921 8.2 135K
135  The Father 2020 8.2 193K
136  Judgment at Nuremberg 1961 8.3 86K
137  All About Eve 1950 8.2 139K
138  The Truman Show 1998 8.2 1.2M
139  Top Gun: Maverick 2022 8.2 698K
140  Shutter Island 2010 8.2 1.5M
141  There Will Be Blood 2007 8.2 641K
142  Casino 1995 8.2 564K
143  Jurassic Park 1993 8.2 1.1M
144  Ran 1985 8.2 136K
145  The Sixth Sense 1999 8.2 1.1M
146  Pan's Labyrinth 2006 8.2 703K
147  Unforgiven 1992 8.2 436K
148  No Country for Old Men 2007 8.2 1.1M
149  A Beautiful Mind 2001 8.2 987K
150  The Thing 1982 8.2 467K
151  1 2003 8.2 1.2M
152  The Treasure of the Sierra Madre 1948 8.2 132K
153  Yojimbo 1961 8.2 131K
154  Monty Python and the Holy Grail 1975 8.2 570K
155  The Great Escape 1963 8.2 259K
156  Finding Nemo 2003 8.2 1.1M
157  Prisoners 2013 8.2 810K
158  Rashomon 1950 8.2 181K
159  Howl's Moving Castle 2004 8.2 450K
160  The Elephant Man 1980 8.2 259K
161  Chinatown 1974 8.1 350K
162  Dial M for Murder 1954 8.2 189K
163  Gone with the Wind 1939 8.2 334K
164  V for Vendetta 2005 8.2 1.2M
165  Lock, Stock and Two Smoking Barrels 1998 8.1 617K
166  The Secret in Their Eyes 2009 8.2 222K
167  Inside Out 2015 8.1 786K
168  Raging Bull 1980 8.1 380K
169  Three Billboards Outside Ebbing, Missouri 2017 8.1 555K
170  Trainspotting 1996 8.1 726K
171  The Bridge on the River Kwai 1957 8.1 233K
172  Fargo 1996 8.1 727K
173  Spider-Man: No Way Home 2021 8.2 880K
174  Klaus 2019 8.2 190K
175  Catch Me If You Can 2002 8.1 1.1M
176  Warrior 2011 8.1 498K
177  Gran Torino 2008 8.1 815K
178  My Neighbor Totoro 1988 8.1 381K
179  Million Dollar Baby 2004 8.1 722K
180  Harry Potter and the Deathly Hallows: Part 2 2011 8.1 949K
181  Children of Heaven 1997 8.2 81K
182  12 Years a Slave 2013 8.1 742K
183  Blade Runner 1982 8.1 823K
184  Before Sunrise 1995 8.1 340K
185  Ben-Hur 1959 8.1 254K
186  Barry Lyndon 1975 8.1 183K
187  The Grand Budapest Hotel 2014 8.1 887K
188  Gone Girl 2014 8.1 1.1M
189  Hacksaw Ridge 2016 8.1 595K
190  The Gold Rush 1925 8.1 119K
191  Memories of Murder 2003 8.1 217K
192  In the Name of the Father 1993 8.1 187K
193  Dead Poets Society 1989 8.1 547K
194  Mad Max: Fury Road 2015 8.1 1.1M
195  Wild Tales 2014 8.1 216K
196  The Deer Hunter 1978 8.1 362K
197  The General 1926 8.1 98K
198  On the Waterfront 1954 8.1 165K
199  2001 8.1 979K
200  1924 8.2 57K
201  The Third Man 1949 8.1 182K
202  Jaws 1975 8.1 660K
203  How to Train Your Dragon 2010 8.1 801K
204  Wild Strawberries 1957 8.1 115K
205  The Wages of Fear 1953 8.2 67K
206  Mary and Max 2009 8.1 187K
207  Smith Goes to Washington 1939 8.1 121K
208  Ratatouille 2007 8.1 826K
209  Ford v Ferrari 2019 8.1 475K
210  Tokyo Story 1953 8.1 69K
211  The Big Lebowski 1998 8.1 861K
212  Room 2015 8.1 451K
213  The Seventh Seal 1957 8.1 199K
214  Rocky 1976 8.1 629K
215  Logan 2017 8.1 832K
216  Spotlight 2015 8.1 502K
217  Hotel Rwanda 2004 8.1 372K
218  The Terminator 1984 8.1 925K
219  Platoon 1986 8.1 440K
220  Godzilla Minus One 2023 8.2 54K
221  The Passion of Joan of Arc 1928 8.1 61K
222  La haine 1995 8.1 197K
223  Before Sunset 2004 8.1 288K
224  The Best Years of Our Lives 1946 8.1 71K
225  Pirates of the Caribbean: The Curse of the Black Pearl 2003 8.1 1.2M
226  The Exorcist 1973 8.1 455K
227  Rush 2013 8.1 514K
228  Network 1976 8.1 171K
229  Stand by Me 1986 8.1 442K
230  Jai Bhim 2021 8.7 217K
231  The Wizard of Oz 1939 8.1 429K
232  The Incredibles 2004 8.0 809K
233  Hachi: A Dog's Tale 2009 8.1 312K
234  The Handmaiden 2016 8.1 173K
235  Into the Wild 2007 8.1 658K
236  My Father and My Son 2005 8.2 93K
237  The Sound of Music 1965 8.1 261K
238  The Grapes of Wrath 1940 8.1 100K
239  To Be or Not to Be 1942 8.1 43K
240  The Battle of Algiers 1966 8.1 66K
241  Groundhog Day 1993 8.0 685K
242  Amores Perros 2000 8.1 253K
243  Rebecca 1940 8.1 147K
244  The Iron Giant 1999 8.1 228K
245  Cool Hand Luke 1967 8.1 189K
246  The Help 2011 8.1 493K
247  It Happened One Night 1934 8.1 112K
248  Aladdin 1992 8.0 467K
249  Dances with Wolves 1990 8.0 291K
250  Paris, Texas 1984 8.1 119K

### 2. Creating a DataFrame

##### Create a data frame of the web-scraping top_rated_movies as 'Top_movies'.

In [30]:

url = 'https://www.imdb.com/chart/top/'

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

ul_class = "ipc-metadata-list ipc-metadata-list--dividers-between sc-a1e81754-0 eBRbsI compact-list-view ipc-metadata-list--base"

div_class = "sc-b189961a-0 hBZnfJ cli-children" 

try:
    
    response = requests.get(url, headers=headers)
    response.raise_for_status()  


    soup = BeautifulSoup(response.text, 'html.parser')
    movies = soup.find('ul', class_=ul_class).find_all('div', class_=div_class)
    
    # Initialize lists to store movie details
    ranks = []
    titles = []
    years = []
    ratings = []
    votes = []

    
    for movie in movies:
        rank = movie.find('h3', class_="ipc-title__text").text.split('.')[0]
        title = movie.find('h3', class_="ipc-title__text").text.split('.')[-1].strip()
        release_year = movie.find('div', class_="sc-b189961a-7 feoqjK cli-title-metadata").span.text.strip()
        rating = movie.find('span', class_="sc-b189961a-1 kcfvgk").span.text.split()[0]
        vote_count = movie.find('span', class_="sc-b189961a-1 kcfvgk").span.text.split()[-1].strip('()')

        # Append movie details to respective lists
        ranks.append(rank)
        titles.append(title)
        years.append(release_year)
        ratings.append(rating)
        votes.append(vote_count)
    
    # Create a DataFrame from the collected movie details
    Top_movies = pd.DataFrame({'Rank': ranks, 'Title': titles, 'Release_Year': years, 'Rating': ratings, 'Vote_Count': votes})
    print(Top_movies)
        
except Exception as e:
    # Print any exceptions that occur during the process
    print(e)

    Rank                     Title Release_Year Rating Vote_Count
0      1  The Shawshank Redemption         1994    9.3       2.9M
1      2             The Godfather         1972    9.2         2M
2      3           The Dark Knight         2008    9.0       2.9M
3      4     The Godfather Part II         1974    9.0       1.4M
4      5              12 Angry Men         1957    9.0       866K
..   ...                       ...          ...    ...        ...
245  246                  The Help         2011    8.1       493K
246  247     It Happened One Night         1934    8.1       112K
247  248                   Aladdin         1992    8.0       467K
248  249        Dances with Wolves         1990    8.0       291K
249  250              Paris, Texas         1984    8.1       119K

[250 rows x 5 columns]

### 3.Exporting to  CSV File

##### Create a CSV file of the 'Top_movies' data frame as 'imdb_top_movies.csv'.

In [9]:

# Save the DataFrame 'Top_movies' to a CSV file named 'imdb_top_movies.csv'
Top_movies.to_csv('imdb_top_movies.csv', index=False)

# Print a message indicating that the CSV file has been saved successfully
print("CSV file saved successfully.")

CSV file saved successfully.

##### Load the CSV file 'imdb_top_movies' by using pandas.

In [31]:

# Read the CSV file 'imdb_top_movies.csv' into a DataFrame named 'Top_movies'
Top_movies = pd.read_csv('imdb_top_movies.csv')

# Display the DataFrame 'Top_movies'
Top_movies

     Rank                     Title  Release_Year  Rating Vote_Count
0       1  The Shawshank Redemption          1994     9.3       2.9M
1       2             The Godfather          1972     9.2         2M
2       3           The Dark Knight          2008     9.0       2.9M
3       4     The Godfather Part II          1974     9.0       1.4M
4       5              12 Angry Men          1957     9.0       866K
..    ...                       ...           ...     ...        ...
245   246                  The Help          2011     8.1       493K
246   247     It Happened One Night          1934     8.1       112K
247   248                   Aladdin          1992     8.0       467K
248   249        Dances with Wolves          1990     8.0       291K
249   250              Paris, Texas          1984     8.1       119K

[250 rows x 5 columns]